// <auto-generated />
using System;
using API_CRUD.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_CRUD.Model.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 105, DateTimeKind.Local).AddTicks(1967),
                            Password = "123",
                            Status = 1,
                            UserName = "beast"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 105, DateTimeKind.Local).AddTicks(2890),
                            Password = "123",
                            Status = 1,
                            UserName = "savage"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 105, DateTimeKind.Local).AddTicks(2928),
                            Password = "123",
                            Status = 1,
                            UserName = "bear"
                        });
                });

            modelBuilder.Entity("API_CRUD.Model.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 101, DateTimeKind.Local).AddTicks(2396),
                            Description = "Best boxing gloves are Everlast..!",
                            Name = "Boxing Gloves",
                            Slug = "boxing-gloves",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 102, DateTimeKind.Local).AddTicks(5974),
                            Description = "Best protective equipment are Everlast..!",
                            Name = "Protective Equipment",
                            Slug = "protective-equipment",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 1, 17, 12, 0, 4, 102, DateTimeKind.Local).AddTicks(6041),
                            Description = "Best head gear are Everlast..!",
                            Name = "Head Gear",
                            Slug = "head-gear",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
